CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h

add lGetTraitCityStateFriendshipModifier

---

CvGameCoreDLL_Expansion2/CvAStar.cpp
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvSiteEvaluationClasses.cpp
CvGameCoreDLL_Expansion2/CvTechClasses.cpp
CvGameCoreDLL_Expansion2/CvTradeClasses.cpp
CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h

Japanese Trait bugfix

---

CvGameCoreDLL_Expansion2/CvPlot.cpp

add UA terrian bouns when Improment building

---

(1) CIV5MPDLL/DB/NewTableChanges.sql
CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp
CvGameCoreDLL_Expansion2/CvPromotionClasses.h
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/CvUnit.h
CvGameCoreDLL_Expansion2/CvUnitCombat.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h

ALTER TABLE UnitPromotions ADD 'WorkRateMod' INTEGER DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'AoEWhileFortified' INTEGER DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'AOEDamageOnKill' INTEGER DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'CaptureDefeatedEnemyChance' BOOLEAN DEFAULT 0;
ALTER TABLE UnitPromotions ADD COLUMN 'BarbarianCombatBonus' INTEGER DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'CannotBeCaptured' BOOLEAN DEFAULT 0;

new promotion

---

(1) CIV5MPDLL/DB/CITY_SCALES/CityScales.sql
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvCity.h
CvGameCoreDLL_Expansion2/CvCityScaleClasses.cpp
CvGameCoreDLL_Expansion2/CvCityScaleClasses.h
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvPolicyClasses.cpp

can give free buildings according traits and policies

Feat: more funcitons about city scale

---

CvGameCoreDLL_Expansion2/CvCity.cpp

Trait_BuildingClassYieldChanges BUG Fix.

Trait_BuildingClassYieldChanges BUG Fix.

---

CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvUnitCombat.cpp

fix: PLOT_POPUP in doInstantYield

---

(1) CIV5MPDLL/CustomModOptions.xml
(1) CIV5MPDLL/DB/RELIGION/Belief_Table_Changes.sql
CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp
CvGameCoreDLL_Expansion2/CvBeliefClasses.h
CvGameCoreDLL_Expansion2/CvCultureClasses.cpp
CvGameCoreDLL_Expansion2/CvReligionClasses.cpp

注释了int CvCityCulture::GetYieldFromImprovements(YieldTypes eYield) const计算额外周围产出部分的代码(会导致重复计算摩艾石像的文化)

add: LandmarksTourismPercent From Religion

---

(1) CIV5MPDLL/DB/NewTableChanges.sql
CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp
CvGameCoreDLL_Expansion2/CvPromotionClasses.h
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/CvUnit.h
CvGameCoreDLL_Expansion2/CvUnitCombat.cpp
CvGameCoreDLL_Expansion2/CvUnitCombat.h

增加了三个内嵌LUA接口分别对应攻击后恢复攻击次数、恢复生命值、恢复移动力

add: Unit bouns from Attack Damage

---

(1) CIV5MPDLL/DB/BUILDINGS/Building_InstantYield.xml
CvGameCoreDLL_Expansion2/CvAStar.cpp
CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp
CvGameCoreDLL_Expansion2/CvBuildingClasses.h
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvCity.h
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvSiteEvaluationClasses.cpp
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/CvUnit.h
CvGameCoreDLL_Expansion2/CvUnitCombat.cpp

1.还原了Building_ImprovementResourcesQuantity
2.稍微优化了山脉城市的移民ai判定并将倾向改回
3.马穆鲁克的攻击获得信仰机制不再只与人类作战生效

Revert Building_ImprovementResourcesQuantity

---

CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
CvGameCoreDLL_Expansion2/CvPlayerAI.cpp

1.恢复了ai烧城判定
2.修复了城邦结算已死亡文明任务的bug

Minor Quests and City Raze fix

---

(1) CIV5MPDLL/DB/RELIGION/Belief_Table_Changes.sql
CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp
CvGameCoreDLL_Expansion2/CvBeliefClasses.h
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvCity.h
CvGameCoreDLL_Expansion2/CvCityCitizens.cpp
CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp
CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaCity.h

Dev religion changes

---

(1) CIV5MPDLL/DB/RELIGION/Belief_Table_Changes.sql
CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp
CvGameCoreDLL_Expansion2/CvBeliefClasses.h
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvReligionClasses.cpp

1.增加了信条给圣城提供伟人点的接口（由于这个接口没有设置ai倾向）
2.把CvPlayer::processBuilding末尾的countNumBuildings换成了set以避免遍历所有城市，并进行了简单的测试

feature: Great Person Points HolyCity

---

(1) CIV5MPDLL/DB/_TEXT/AllText_en_US.xml
(1) CIV5MPDLL/DB/_TEXT/AllText_zh_CN.xml
(1) CIV5MPDLL/DB/_TEXT/AllText_zh_Hant_HK.xml
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvCultureClasses.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp

1.修复了城市文化的一个错误加成
2.增加了城市面板魅力加成的提示
3.依据VP代码补上了一个函数的返回值

fix: getBaseYieldRateModifier

---

(1) CIV5MPDLL/DB/GLOBAL/Resolutions.sql
(1) CIV5MPDLL/DB/RELIGION/Belief_Table_Changes.sql
CvGameCoreDLL_Expansion2/CvBeliefClasses.cpp
CvGameCoreDLL_Expansion2/CvBeliefClasses.h
CvGameCoreDLL_Expansion2/CvCityCitizens.cpp
CvGameCoreDLL_Expansion2/CvMinorCivAI.cpp
CvGameCoreDLL_Expansion2/CvMinorCivAI.h
CvGameCoreDLL_Expansion2/CvReligionClasses.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaCity.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaCity.h

1.增加了同宗教增加城邦影响力恢复速率的接口
2.将冷战的代码移植SP
3.修复交换城市地块导致不能锁住城市人口的问题

feature: SameReligionMinorRecoveryModifier

---

CvGameCoreDLL_Expansion2/CvCity.cpp

fix: Miscounted the number of Garrisoned Units 3

---

CvGameCoreDLL_Expansion2/CvCity.cpp

YIELD  GREAT GENERAL

---

(1) CIV5MPDLL/CustomModOptions.xml
(1) CIV5MPDLL/DB/TRAITS/DDL_Traits.sql
CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvCity.h
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvPlayer.h
CvGameCoreDLL_Expansion2/CvTeam.cpp
CvGameCoreDLL_Expansion2/CvTradeClasses.cpp
CvGameCoreDLL_Expansion2/CvTradeClasses.h
CvGameCoreDLL_Expansion2/CvTraitClasses.cpp
CvGameCoreDLL_Expansion2/CvTraitClasses.h
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h

feture: trait-TradeRouteGoldBonus
perf: GetTradeConnectionYourBuildingValueTimes100
perf: GetTradeRouteRange()
fix: no pre-Building in func canConstruct

feture: trait-TradeRouteGoldBonus

---

(1) CIV5MPDLL/DB/NewTableChanges.sql
CvGameCoreDLL_Expansion2/CvBuildingClasses.cpp
CvGameCoreDLL_Expansion2/CvBuildingClasses.h
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvPlayer.h
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/CvUnitMovement.cpp

TileTurnDamageGlobal

---

CvGameCoreDLL_Expansion2/CvCity.cpp
CvGameCoreDLL_Expansion2/CvPlayer.cpp
CvGameCoreDLL_Expansion2/CvPlayer.h
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaPlayer.h

* feature: UCFromExtra
* feature: SetLostUC()
* fix: forbid default building/unit when player marked it
* fix: can purchase GPerson when has UU count
* fix: Free Buildings && UpgradeUnitType

feature: UCFromExtra (#15)

---

(1) CIV5MPDLL/DB/NewTableChanges.sql
CvGameCoreDLL_Expansion2/CvPromotionClasses.cpp
CvGameCoreDLL_Expansion2/CvPromotionClasses.h
CvGameCoreDLL_Expansion2/CvUnit.cpp
CvGameCoreDLL_Expansion2/CvUnit.h
CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.cpp
CvGameCoreDLL_Expansion2/Lua/CvLuaUnit.h

* Promotion:MaintenanceCost ---------

Extra maintnce (#16)

---

(1) CIV5MPDLL/CustomModOptions.xml
CvGameCoreDLL_Expansion2/CvAStar.cpp
CvGameCoreDLL_Expansion2/CvUnit.cpp

fix: civilians cannot enter city in BREAK_BREAK_CIVILIAN_RESTRICTIONS
